language: node_js
sudo: false
node_js:
  - "7.6"
  - "7.10"

cache:
  yarn: true
  directories:
  - node_modules/

before_install:
  - npm install -g nyc codecov

install:
  - yarn
script:
  - npm run coverage

after_success:
  - nyc report --reporter=lcov > coverage.lcov && codecov
